--
-- PostgreSQL database dump
--

\restrict jio4YxXmYb9ms2oNv8DBUnE0PpTHIllOOsNcW3EJ39BSjWHqqGGjrXB2IfCIZtn

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-10 09:11:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 17881)
-- Name: acto_admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.acto_admin (
    id integer NOT NULL,
    numerado integer,
    fecha_numerado timestamp with time zone,
    url_acto text,
    fecha_creacion date,
    tipo_acto character varying(15),
    etapa_id integer,
    nivel_auxiliar boolean
);


ALTER TABLE public.acto_admin OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17887)
-- Name: acto_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.acto_admin_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.acto_admin_id_seq OWNER TO postgres;

--
-- TOC entry 5324 (class 0 OID 0)
-- Dependencies: 220
-- Name: acto_admin_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.acto_admin_id_seq OWNED BY public.acto_admin.id;


--
-- TOC entry 221 (class 1259 OID 17888)
-- Name: acto_admin_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.acto_admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acto_admin_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17889)
-- Name: cesacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cesacion (
    id integer NOT NULL,
    tipo_cesacion_id integer,
    etapa_id integer
);


ALTER TABLE public.cesacion OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17893)
-- Name: comunicacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comunicacion (
    id integer NOT NULL,
    numerado integer,
    fecha_envio date,
    acto_admin_id integer,
    fecha_numerado date,
    fecha_creacion date,
    url_documento text
);


ALTER TABLE public.comunicacion OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17899)
-- Name: comunicacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.comunicacion_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.comunicacion_id_seq OWNER TO postgres;

--
-- TOC entry 5325 (class 0 OID 0)
-- Dependencies: 224
-- Name: comunicacion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.comunicacion_id_seq OWNED BY public.comunicacion.id;


--
-- TOC entry 225 (class 1259 OID 17900)
-- Name: comunicacion_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comunicacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comunicacion_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17901)
-- Name: decision_fondo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.decision_fondo (
    id integer NOT NULL,
    tipo_sancion_id integer,
    detalle text,
    etapa_id integer
);


ALTER TABLE public.decision_fondo OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17907)
-- Name: decision_fondo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.decision_fondo ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.decision_fondo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17908)
-- Name: documento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documento (
    id integer NOT NULL,
    nombre character varying(100),
    url_documento text,
    fecha_subida timestamp with time zone,
    etapa_id integer
);


ALTER TABLE public.documento OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17914)
-- Name: documento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.documento_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.documento_id_seq OWNER TO postgres;

--
-- TOC entry 5326 (class 0 OID 0)
-- Dependencies: 229
-- Name: documento_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.documento_id_seq OWNED BY public.documento.id;


--
-- TOC entry 230 (class 1259 OID 17915)
-- Name: documento_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.documento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documento_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 17916)
-- Name: ejecucion_sancion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ejecucion_sancion (
    id integer NOT NULL,
    cobro_coactivo boolean,
    disposicion boolean,
    ruia boolean,
    etapa_id integer,
    auto_admin text,
    fecha_auto date,
    cobro_coactivo_doc_url text,
    ruia_doc_url text,
    auto_doc_url text,
    memorando_doc_url text,
    memorando boolean
);


ALTER TABLE public.ejecucion_sancion OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17922)
-- Name: ejecucion_sancion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ejecucion_sancion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ejecucion_sancion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17923)
-- Name: etapa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etapa (
    id integer NOT NULL,
    expediente_radicado text,
    tipo_etapa_id integer,
    fecha_inicio timestamp without time zone
);


ALTER TABLE public.etapa OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17929)
-- Name: etapa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.etapa ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.etapa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17930)
-- Name: expediente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expediente (
    radicado character varying(10) NOT NULL,
    nombre_expediente character varying(7),
    motivo_afectacion character varying(200),
    fecha_creacion timestamp with time zone NOT NULL,
    encargado_id bigint,
    direccion character varying(100),
    vereda_id integer,
    id_auxiliar bigint NOT NULL,
    archivado boolean,
    fecha_archivado timestamp with time zone
);


ALTER TABLE public.expediente OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17936)
-- Name: expediente_id_auxiliar_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expediente ALTER COLUMN id_auxiliar ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.expediente_id_auxiliar_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 17937)
-- Name: expediente_recurso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expediente_recurso (
    expediente_radicado text NOT NULL,
    recurso_id integer NOT NULL
);


ALTER TABLE public.expediente_recurso OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17944)
-- Name: formulacion_cargos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formulacion_cargos (
    id integer NOT NULL,
    descargos boolean,
    etapa_id integer,
    url_documento text
);


ALTER TABLE public.formulacion_cargos OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17950)
-- Name: formulacion_cargos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formulacion_cargos ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.formulacion_cargos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17951)
-- Name: involucrado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.involucrado (
    id integer NOT NULL,
    numero_documento bigint,
    tipo_documento character varying(20),
    nombre character varying(100),
    celular bigint,
    correo character varying(254),
    digito_verificacion character varying(2)
);


ALTER TABLE public.involucrado OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17955)
-- Name: involucrado_expediente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.involucrado_expediente (
    involucrado_id integer NOT NULL,
    expediente_radicado text NOT NULL
);


ALTER TABLE public.involucrado_expediente OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17962)
-- Name: involucrado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.involucrado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.involucrado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 17963)
-- Name: involucrado_notificacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.involucrado_notificacion (
    id integer NOT NULL,
    notificacion_id integer,
    involucrado_id integer,
    numerado integer,
    fecha_envio_citacion date,
    fecha_constancia_citacion date,
    notificacion_exitosa boolean,
    fecha_numerado date,
    url_documento text,
    tipo_notificacion_id integer,
    fecha_notificacion date
);


ALTER TABLE public.involucrado_notificacion OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17969)
-- Name: involucrado_notificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.involucrado_notificacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.involucrado_notificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 17970)
-- Name: ley_1333_2009_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cesacion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ley_1333_2009_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17971)
-- Name: log_auditoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.log_auditoria (
    id integer NOT NULL,
    expediente_radicado text,
    tabla_afectada character varying(30) NOT NULL,
    id_registro character varying(20),
    tipo_operacion character varying(10) NOT NULL,
    usuario_id bigint,
    fecha timestamp without time zone DEFAULT now(),
    descripcion text,
    datos_anteriores jsonb,
    datos_nuevos jsonb
);


ALTER TABLE public.log_auditoria OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 17980)
-- Name: log_auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.log_auditoria_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.log_auditoria_id_seq OWNER TO postgres;

--
-- TOC entry 5327 (class 0 OID 0)
-- Dependencies: 247
-- Name: log_auditoria_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.log_auditoria_id_seq OWNED BY public.log_auditoria.id;


--
-- TOC entry 248 (class 1259 OID 17981)
-- Name: medida_preventiva; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medida_preventiva (
    id integer NOT NULL,
    tipo_medida_id integer,
    cantidad text,
    especie text,
    estado_medida boolean,
    etapa_id integer
);


ALTER TABLE public.medida_preventiva OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17987)
-- Name: medida_preventiva_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medida_preventiva ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medida_preventiva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 17988)
-- Name: municipio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.municipio (
    id integer NOT NULL,
    nombre character varying(20)
);


ALTER TABLE public.municipio OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 17992)
-- Name: municipio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.municipio ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.municipio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 17993)
-- Name: nivel_acto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nivel_acto (
    id integer NOT NULL,
    nombre character varying(15)
);


ALTER TABLE public.nivel_acto OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 17997)
-- Name: nivel_acto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.nivel_acto ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.nivel_acto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 17998)
-- Name: notificacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificacion (
    id integer NOT NULL,
    fecha_creacion date,
    acto_admin_id integer
);


ALTER TABLE public.notificacion OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 18002)
-- Name: proceso_notificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificacion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.proceso_notificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 18003)
-- Name: recurso_afectado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recurso_afectado (
    id integer NOT NULL,
    nombre character varying(15) NOT NULL
);


ALTER TABLE public.recurso_afectado OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 18008)
-- Name: recurso_afectado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.recurso_afectado_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.recurso_afectado_id_seq OWNER TO postgres;

--
-- TOC entry 5328 (class 0 OID 0)
-- Dependencies: 257
-- Name: recurso_afectado_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.recurso_afectado_id_seq OWNED BY public.recurso_afectado.id;


--
-- TOC entry 258 (class 1259 OID 18009)
-- Name: recurso_afectado_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recurso_afectado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurso_afectado_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 18010)
-- Name: tipo_cesacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_cesacion (
    id integer NOT NULL,
    nombre text
);


ALTER TABLE public.tipo_cesacion OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 18016)
-- Name: tipo_cesacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_cesacion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tipo_cesacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 18017)
-- Name: tipo_etapa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_etapa (
    id integer NOT NULL,
    nombre character varying(30)
);


ALTER TABLE public.tipo_etapa OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 18021)
-- Name: tipo_etapa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_etapa ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tipo_etapa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 18022)
-- Name: tipo_medida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_medida (
    id integer NOT NULL,
    nombre text
);


ALTER TABLE public.tipo_medida OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 18028)
-- Name: tipo_medida_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_medida ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tipo_medida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 18029)
-- Name: tipo_notificacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_notificacion (
    id integer NOT NULL,
    nombre character varying(15)
);


ALTER TABLE public.tipo_notificacion OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 18033)
-- Name: tipo_notificacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_notificacion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tipo_notificacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 18034)
-- Name: tipo_sancion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_sancion (
    id integer NOT NULL,
    nombre text
);


ALTER TABLE public.tipo_sancion OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 18040)
-- Name: tipo_sancion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_sancion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tipo_sancion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 18041)
-- Name: vereda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vereda (
    id integer NOT NULL,
    nombre character varying(25),
    municipio_id integer
);


ALTER TABLE public.vereda OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 18045)
-- Name: vereda_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vereda ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.vereda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4978 (class 2604 OID 18046)
-- Name: log_auditoria id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_auditoria ALTER COLUMN id SET DEFAULT nextval('public.log_auditoria_id_seq'::regclass);



--
-- TOC entry 5270 (class 0 OID 17889)
-- Dependencies: 222
-- Data for Name: cesacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cesacion (id, tipo_cesacion_id, etapa_id) FROM stdin;
\.



--
-- TOC entry 5274 (class 0 OID 17901)
-- Dependencies: 226
-- Data for Name: decision_fondo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.decision_fondo (id, tipo_sancion_id, detalle, etapa_id) FROM stdin;
\.



--
-- TOC entry 5298 (class 0 OID 17988)
-- Dependencies: 250
-- Data for Name: municipio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.municipio (id, nombre) FROM stdin;
1	Almeida
2	Boyacá
3	Campohermoso
4	Chinavita
5	Chivor
6	Ciénega
7	Garagoa
8	Guateque
9	Guayatá
10	Jenesano
11	La Capilla
12	Macanal
13	Nuevo Colón
14	Pachavita
15	Ramiriquí
16	San Luis de Gaceno
17	Santa María
18	Somondoco
19	Sutatenza
20	Tenza
21	Tibaná
22	Turmequé
23	Ventaquemada
24	Viracachá
25	Úmbita
\.


--
-- TOC entry 5300 (class 0 OID 17993)
-- Dependencies: 252
-- Data for Name: nivel_acto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nivel_acto (id, nombre) FROM stdin;
1	recurso
2	decision
\.

--
-- TOC entry 5304 (class 0 OID 18003)
-- Dependencies: 256
-- Data for Name: recurso_afectado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recurso_afectado (id, nombre) FROM stdin;
1	Agua
2	Aire
3	Bosque
4	Fauna
5	Flora
6	Suelo
\.


--
-- TOC entry 5307 (class 0 OID 18010)
-- Dependencies: 259
-- Data for Name: tipo_cesacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_cesacion (id, nombre) FROM stdin;
1	Muerte de investigado
2	No es constitutivo de infracción ambiental
3	Conducta investigada no es imputable al presunto infractor
4	La actividad esta legalmente amparada/autorizada
\.


--
-- TOC entry 5309 (class 0 OID 18017)
-- Dependencies: 261
-- Data for Name: tipo_etapa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_etapa (id, nombre) FROM stdin;
1	DETALLE MEDIDA PREVENTIVA
2	INDAGACION PRELIMINAR
3	PROCEDIMIENTO LEY 1333 DE 2009
5	APERTURA ETAPA PROBATORIA
4	FORMULACION DE CARGOS
6	DECISION DE FONDO
7	EJECUCION DE LA SANCION
9	INICIO PROCESO SANCIONATORIO
10	CESACION
11	CIERRE ETAPA PROBATORIA
12	PROBATORIA DE RECURSO
\.


--
-- TOC entry 5311 (class 0 OID 18022)
-- Dependencies: 263
-- Data for Name: tipo_medida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_medida (id, nombre) FROM stdin;
1	Decomiso preventivo
2	Suspensión del proyecto
3	Estudios y evaluaciones requeridas para conocer la naturaleza de lo daños
4	Suspensión de actividades o de obras
5	Clausura temporal
6	Decomiso preventivo
7	Aprehensión preventiva
8	Congelación o suspensión de venta-empleo
9	Amonestación escrita
10	Elaboración de estudios ambientales
\.


--
-- TOC entry 5313 (class 0 OID 18029)
-- Dependencies: 265
-- Data for Name: tipo_notificacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_notificacion (id, nombre) FROM stdin;
1	Personal
2	Correo
3	Publicación
\.


--
-- TOC entry 5315 (class 0 OID 18034)
-- Dependencies: 267
-- Data for Name: tipo_sancion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tipo_sancion (id, nombre) FROM stdin;
1	Amonestación escrita
2	Cierre temporal o definitivo
3	Revocatorio o caducidad de licencia ambiental, autorización, concesión, permiso o registro
4	Demolición de obra a costa del infractor
5	Decomiso preventivo de especímenes, especies silvestres
6	Restitución de especímenes de flora y fauna silvestres o acuática
\.


--
-- TOC entry 5317 (class 0 OID 18041)
-- Dependencies: 269
-- Data for Name: vereda; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vereda (id, nombre, municipio_id) FROM stdin;
1	Belen	1
2	Curiavaca Abajo	1
3	Curiavaca Arriba	1
4	Molinos	1
5	Rosal	1
6	Tibaita	1
7	Tona	1
8	Umbavita	1
9	Yavir	1
11	Huerta Chica	2
12	Huerta Grande Sector 1	2
13	Huerta Grande Sector 2	2
14	Pachaquira	2
15	Rique	2
16	Rupaguata	2
17	Siraquita	2
18	Soconsaque Occidente	2
19	Soconsaque Oriente	2
20	Vanegas Sector Norte	2
21	Vanegas Sector Sur	2
22	Castañal	3
23	Cañadas	3
24	Cedros Centro	3
26	Choma	3
27	Colombia	3
28	El Limon	3
29	El Rodeo	3
30	Encenillo	3
31	Guamal	3
32	Hoya Grande	3
33	Huerta Vieja	3
34	Macanalito	3
35	Palmichal	3
36	Sababetas	3
37	San Agustin	3
38	San José	3
39	Teguas	3
40	Toldo	3
41	Yoteguengue	3
42	Centro Abajo	4
43	Centro Arriba	4
44	Curavita	4
45	Fusa	4
46	Guayabal	4
47	Jordan	4
48	Juntas	4
49	Montejo	4
50	Mundo Nuevo	4
51	Quinchos	4
52	Sicha	4
53	Usillo	4
54	Valle	4
55	Zanja Abajo	4
56	Zanja Arriba	4
57	Alimentos	5
58	Camoyo	5
60	Chivor Chiquita	5
61	El Higueron	5
62	El Pino	5
63	Guali	5
64	Jagua la Playa	5
65	La Esmeralda	5
66	La Esperanza	5
67	San Cayetano	5
68	San Francisco	5
69	San Martin	5
70	Sinai	5
71	Albanil	6
72	Calabazal	6
73	Cebadal	6
74	El Plan	6
75	Espinal	6
76	Guatareta	6
77	Manzanos	6
78	Piedra Larga	6
79	Reavita	6
80	San Vicente	6
81	Tapias	6
82	Arada Chiquita	7
83	Arada Grande	7
84	Bancos de Arada	7
85	Bancos de Paramo	7
86	Bojaca	7
87	Caldera Abajo	7
88	Caldera Arriba	7
89	Caracol	7
90	Cienaga Guarumal	7
91	Cienaga Tablon	7
92	Cienaga Valvanera	7
93	Cuanica Abajo	7
94	Cucharero	7
95	Cunica Arriba	7
96	Cunica Molino	7
97	Curjal	7
98	Escobal	7
99	Fumbaque	7
100	Guayabal	7
101	Hipaquira	7
102	Maciecal	7
103	Manzanos Abajo	7
104	Quicua Abajo	7
105	Quicua Arriba	7
106	Resguardo Abajo	7
107	Resguardo Arriba	7
108	Resguardo Machilero	7
109	Resguardo Manzanos Arriba	7
110	Senda Abajo	7
111	Senda Arriba	7
112	Cantoras	8
113	Chinquica	8
114	Chorro de Oro	8
115	Chorro Tinto	8
116	Gaunza Abajo	8
117	Gaunza Arriba	8
118	Goteras	8
119	Juntas	8
120	Llano Grande	8
121	Mortiño	8
122	Munanta	8
123	Piedra Parada	8
124	Pozos	8
125	Puentes	8
126	Rosales	8
127	Sibata	8
128	Siravita	8
129	Suaitoque	8
130	Tincachoque	8
131	Ubajuca	8
132	Barro Negro	9
133	Caliche Abajo	9
134	Caliche Arriba	9
135	Carrizal	9
136	Chitavita	9
137	Ciavita Ii	9
138	Ciavita I	9
139	Ciavita Iii	9
140	El Tablon	9
141	Escaleras	9
142	Fonsaque Abajo	9
143	Fonsaque Arriba	9
144	Guaquira	9
145	Guarumal	9
146	Guavita	9
147	Hato Viejo	9
148	Las Juntas	9
149	Plaza Abajo	9
150	Plaza Arriba	9
151	Potreritos	9
152	Rincon Abajo	9
153	Rincon Arriba	9
154	Romaquira	9
155	Sochaquira Abajo	9
156	Sochaquira Arriba	9
157	Sunuba	9
158	Tencua Abajo	9
159	Tencua Arriba	9
160	Volcan	9
161	Baganique Alto	10
162	Baganique Bajo	10
163	Baganique Medio	10
164	Cardonal	10
165	Carrizal	10
166	Dulceyes	10
167	Foraquira	10
168	Naranjos	10
169	Nonceta	10
170	Paeces	10
171	Palenque	10
172	Pantano Colorado	10
173	Piranguata	10
174	Pulidos	10
175	Rodriguez	10
176	Soleres	10
177	Supaneca	10
178	Volador	10
179	Barro Blanco Abajo	11
180	Barroblanco Arriba	11
181	Camagoa	11
183	Chaguatoque	11
184	Chicio	11
185	Hato	11
186	Palma Abajo	11
187	Palma Arriba	11
188	Paramo	11
189	Peñas	11
190	Suntafita	11
191	Truco	11
192	Ubaneca	11
193	Zinc	11
194	Agua Blanca	12
196	Datil Chiquito	12
197	Datil Grande	12
198	Guavio	12
199	La Mesa	12
200	La Vega	12
201	Limon	12
202	Media Estancia	12
203	Muceño	12
204	Naranjos	12
205	Pantanos	12
206	Perdiguiz Chiquito	12
207	Perdiguiz Grande	12
208	Peña Blanca	12
209	Quebrada Negra	12
210	Tibacota	12
211	Vijagual	12
212	Volador	12
213	Alfaras	13
214	Aposentos	13
215	Carbonera	13
216	Centro Rural	13
217	El Uvo	13
218	Fiota	13
219	Invita	13
220	Jabonera	13
221	Llano Grande	13
222	Pavaquirá	13
223	Potreros	13
224	Sorca	13
225	Tapias	13
226	Tejar Abajo	13
227	Tejar Arriba	13
228	Zapatero	13
229	Agua Quina	14
230	Buenavista	14
232	Guacal	14
233	Hato Grande	14
234	Llano Grande	14
235	Pie de Peña	14
236	Soaquira	14
237	Caicedos	15
238	Chuscal	15
239	Comun	15
240	El Pabellon	15
241	Escobal	15
242	Faravita	15
243	Farquenta	15
244	Fernandez	15
245	Fragua - Hervideros	15
246	Gachantiva	15
247	Guacamayas	15
248	Guayabal	15
249	Hervidero	15
250	Hortigal	15
251	Naguata	15
252	Pantanno Largo	15
253	Peñas	15
254	Potreros	15
255	Resguardo Alto	15
256	Resguardo Bajo	15
257	Romazal	15
258	Rosal	15
259	Santana	15
260	Santuario	15
261	Agua Buena	16
262	Arrayanes	16
263	Caracol	16
264	Catatumbo	16
265	Caño Blanco	16
266	Caño Grande	16
267	Caño Tigre	16
269	Centro Guamal	16
270	Centro Horizonte	16
271	Cumaral	16
272	El Cairo	16
273	El Carmen	16
274	Gazajarro	16
275	Gazapal	16
276	Granja	16
277	Guichirales	16
278	La Colonia	16
279	La Dorada	16
280	La Dorada del Guavio	16
281	La Esperanza	16
282	La Mesa	16
283	La Selva	16
284	Laderas	16
285	Macanalito	16
286	Marañal	16
287	Monumento	16
288	Pensamiento	16
289	Piñuela	16
290	Planada Seca	16
291	Rio Chiquito	16
292	San Agustín del Chuy	16
293	San Carlos	16
294	San Isidro	16
295	San José del Chuy	16
296	San Pedro	16
297	Santa María	16
298	Tontogue Alto	16
299	Tontogue Bajo	16
300	Balcones	17
301	Calichana	17
302	Carbonera	17
303	Caño Negro	17
304	Ceiba Chiquita	17
305	Ceiba Grande	17
306	Charco Largo	17
307	Culima	17
308	De Planadas	17
309	El Retiro	17
310	Guaduales	17
311	Hormigueros	17
312	Hoya Grande	17
313	La Victoria	17
314	Nazareth	17
315	San Agustín	17
316	San Miguel	17
317	San Rafael	17
318	Santa Cecilia	17
319	Vara Santa	17
320	Barreras	18
321	Bohórquez	18
322	Boya I	18
323	Boya Ii	18
324	Cabrera	18
325	Cayos	18
326	Cobavita	18
327	Cucuavaca	18
328	Guaduas	18
329	Pancupa	18
330	Resguardo	18
331	Richa	18
332	Sabaneta	18
333	San Antonio	18
334	San Sebastian	18
335	Zarzal	18
336	Boqueron	19
337	Gaque	19
338	Guamo	19
339	Irson	19
340	Paramo	19
341	Piedra Larga	19
342	Salitre	19
343	Siguique	19
344	Aposento	20
345	Barzal	20
346	Chaguatoque	20
347	Cora Chiquito	20
348	Cora Grande	20
349	Mutatea	20
350	Quebradas	20
351	Resguardo	20
352	Rucha	20
353	Valle Grande Abajo	20
354	Valle Grande Arriba	20
355	Volcan	20
356	Arrayan	21
357	Batan	21
358	Bayeta	21
359	Carare	21
360	Chiguata	21
361	El Carmen	21
362	Gambita	21
363	Juana Ruiz	21
364	Laja	21
365	Las Juntas	21
366	Lavaderos	21
367	Mangles	21
368	Maranta	21
369	Mombita	21
370	Pie de Peña	21
371	Piedras de Candela	21
372	Quichatoque	21
373	Ruche	21
374	San José	21
375	Sastoque	21
376	Sirama	21
377	Sirata	21
378	Sitanta	21
379	Siuman	21
380	Supaneca Abajo	21
381	Supaneca Arriba	21
382	Suta Abajo	21
383	Suta Arriba	21
384	Zanja	21
386	Chirata	22
387	Chquinquirá	22
388	Guanzaque	22
389	Joraquira	22
390	Joyagua	22
391	Jurata	22
392	Pascata	22
393	Pozo Negro	22
394	Rinchoque	22
395	Rosales	22
396	Siguinique	22
397	Teguaneque	22
398	V Blanco	22
399	Bojirque	23
400	Boqueron	23
401	Capellania	23
402	Choquira	23
403	Compromiso	23
404	El Carmen	23
405	Estancia Grande	23
406	Frutillo	23
407	Hato	23
408	Jurpa	23
409	Mesa	23
410	Montoya	23
411	Nerita	23
412	Nerita Pd Piedra	23
413	Parroquia Vieja	23
414	Puente Poyaca	23
415	Siata	23
416	Sota	23
417	Supata	23
418	Caros	24
420	Chen	24
421	Galindos	24
422	Icarina	24
423	La Isla	24
424	Naranjos	24
425	Parras	24
426	Pirguata	24
427	Pueblo Viejo	24
428	Altamizal	25
429	Boqueron	25
430	Bosque	25
432	Chuscal	25
433	Jupal	25
434	Loma Gorda	25
435	Molino	25
436	Nueve Pilas	25
437	Pavas	25
438	Rosal	25
439	Sisa	25
440	Tambor Chiquito	25
441	Tambor Grande	25
442	Uvero	25
443	Casco Urbano	1
444	Casco Urbano	2
445	Casco Urbano	3
446	Casco Urbano	4
447	Casco Urbano	5
448	Casco Urbano	6
449	Casco Urbano	7
450	Casco Urbano	8
451	Casco Urbano	9
452	Casco Urbano	10
453	Casco Urbano	11
454	Casco Urbano	12
455	Casco Urbano	13
456	Casco Urbano	14
457	Casco Urbano	15
458	Casco Urbano	16
459	Casco Urbano	17
460	Casco Urbano	18
461	Casco Urbano	19
462	Casco Urbano	20
463	Casco Urbano	21
464	Casco Urbano	22
465	Casco Urbano	23
466	Casco Urbano	24
467	Casco Urbano	25
\.


--
-- TOC entry 5329 (class 0 OID 0)
-- Dependencies: 220
-- Name: acto_admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.acto_admin_id_seq', 1, false);


--
-- TOC entry 5330 (class 0 OID 0)
-- Dependencies: 221
-- Name: acto_admin_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.acto_admin_id_seq1', 1, false);


--
-- TOC entry 5331 (class 0 OID 0)
-- Dependencies: 224
-- Name: comunicacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comunicacion_id_seq', 1, false);


--
-- TOC entry 5332 (class 0 OID 0)
-- Dependencies: 225
-- Name: comunicacion_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comunicacion_id_seq1', 1, false);


--
-- TOC entry 5333 (class 0 OID 0)
-- Dependencies: 227
-- Name: decision_fondo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.decision_fondo_id_seq', 1, false);


--
-- TOC entry 5334 (class 0 OID 0)
-- Dependencies: 229
-- Name: documento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.documento_id_seq', 1, false);


--
-- TOC entry 5335 (class 0 OID 0)
-- Dependencies: 230
-- Name: documento_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.documento_id_seq1', 1, false);


--
-- TOC entry 5336 (class 0 OID 0)
-- Dependencies: 232
-- Name: ejecucion_sancion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ejecucion_sancion_id_seq', 1, false);


--
-- TOC entry 5337 (class 0 OID 0)
-- Dependencies: 234
-- Name: etapa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.etapa_id_seq', 1, false);


--
-- TOC entry 5338 (class 0 OID 0)
-- Dependencies: 236
-- Name: expediente_id_auxiliar_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expediente_id_auxiliar_seq', 1, false);


--
-- TOC entry 5339 (class 0 OID 0)
-- Dependencies: 239
-- Name: formulacion_cargos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formulacion_cargos_id_seq', 1, false);


--
-- TOC entry 5340 (class 0 OID 0)
-- Dependencies: 242
-- Name: involucrado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.involucrado_id_seq', 1, false);


--
-- TOC entry 5341 (class 0 OID 0)
-- Dependencies: 244
-- Name: involucrado_notificacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.involucrado_notificacion_id_seq', 1, false);


--
-- TOC entry 5342 (class 0 OID 0)
-- Dependencies: 245
-- Name: ley_1333_2009_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ley_1333_2009_id_seq', 1, false);


--
-- TOC entry 5343 (class 0 OID 0)
-- Dependencies: 247
-- Name: log_auditoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.log_auditoria_id_seq', 1, false);


--
-- TOC entry 5344 (class 0 OID 0)
-- Dependencies: 249
-- Name: medida_preventiva_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medida_preventiva_id_seq', 1, false);


--
-- TOC entry 5345 (class 0 OID 0)
-- Dependencies: 251
-- Name: municipio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.municipio_id_seq', 25, true);


--
-- TOC entry 5346 (class 0 OID 0)
-- Dependencies: 253
-- Name: nivel_acto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.nivel_acto_id_seq', 2, true);


--
-- TOC entry 5347 (class 0 OID 0)
-- Dependencies: 255
-- Name: proceso_notificacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proceso_notificacion_id_seq', 1, false);


--
-- TOC entry 5348 (class 0 OID 0)
-- Dependencies: 257
-- Name: recurso_afectado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recurso_afectado_id_seq', 6, true);


--
-- TOC entry 5349 (class 0 OID 0)
-- Dependencies: 258
-- Name: recurso_afectado_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recurso_afectado_id_seq1', 1, false);


--
-- TOC entry 5350 (class 0 OID 0)
-- Dependencies: 260
-- Name: tipo_cesacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_cesacion_id_seq', 4, true);


--
-- TOC entry 5351 (class 0 OID 0)
-- Dependencies: 262
-- Name: tipo_etapa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_etapa_id_seq', 12, true);


--
-- TOC entry 5352 (class 0 OID 0)
-- Dependencies: 264
-- Name: tipo_medida_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_medida_id_seq', 10, true);


--
-- TOC entry 5353 (class 0 OID 0)
-- Dependencies: 266
-- Name: tipo_notificacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_notificacion_id_seq', 3, true);


--
-- TOC entry 5354 (class 0 OID 0)
-- Dependencies: 268
-- Name: tipo_sancion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tipo_sancion_id_seq', 6, true);


--
-- TOC entry 5355 (class 0 OID 0)
-- Dependencies: 270
-- Name: vereda_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vereda_id_seq', 467, true);


--
-- TOC entry 4981 (class 2606 OID 18048)
-- Name: acto_admin acto_admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.acto_admin
    ADD CONSTRAINT acto_admin_pkey PRIMARY KEY (id);


--
-- TOC entry 5038 (class 2606 OID 18050)
-- Name: involucrado actor_externo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado
    ADD CONSTRAINT actor_externo_pkey PRIMARY KEY (id);


--
-- TOC entry 4993 (class 2606 OID 18052)
-- Name: comunicacion comunicacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comunicacion
    ADD CONSTRAINT comunicacion_pkey PRIMARY KEY (id);


--
-- TOC entry 4995 (class 2606 OID 18054)
-- Name: decision_fondo decision_fondo_etapa_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.decision_fondo
    ADD CONSTRAINT decision_fondo_etapa_id_key UNIQUE (etapa_id);


--
-- TOC entry 4997 (class 2606 OID 18056)
-- Name: decision_fondo decision_fondo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.decision_fondo
    ADD CONSTRAINT decision_fondo_pkey PRIMARY KEY (id);


--
-- TOC entry 5001 (class 2606 OID 18058)
-- Name: documento documento_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documento
    ADD CONSTRAINT documento_pkey PRIMARY KEY (id);


--
-- TOC entry 5006 (class 2606 OID 18060)
-- Name: ejecucion_sancion ejecucion_sancion_etapa_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejecucion_sancion
    ADD CONSTRAINT ejecucion_sancion_etapa_id_key UNIQUE (etapa_id);


--
-- TOC entry 5008 (class 2606 OID 18062)
-- Name: ejecucion_sancion ejecucion_sancion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejecucion_sancion
    ADD CONSTRAINT ejecucion_sancion_pkey PRIMARY KEY (id);


--
-- TOC entry 5013 (class 2606 OID 18064)
-- Name: etapa etapa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etapa
    ADD CONSTRAINT etapa_pkey PRIMARY KEY (id);


--
-- TOC entry 5019 (class 2606 OID 18066)
-- Name: expediente expediente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expediente
    ADD CONSTRAINT expediente_pkey PRIMARY KEY (radicado);


--
-- TOC entry 5027 (class 2606 OID 18068)
-- Name: expediente_recurso expediente_recurso_afectado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expediente_recurso
    ADD CONSTRAINT expediente_recurso_afectado_pkey PRIMARY KEY (expediente_radicado, recurso_id);


--
-- TOC entry 5032 (class 2606 OID 18070)
-- Name: formulacion_cargos formulacion_cargos_etapa_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formulacion_cargos
    ADD CONSTRAINT formulacion_cargos_etapa_id_key UNIQUE (etapa_id);


--
-- TOC entry 5034 (class 2606 OID 18072)
-- Name: formulacion_cargos formulacion_cargos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formulacion_cargos
    ADD CONSTRAINT formulacion_cargos_pkey PRIMARY KEY (id);


--
-- TOC entry 5047 (class 2606 OID 18074)
-- Name: involucrado_expediente involucrado_expediente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado_expediente
    ADD CONSTRAINT involucrado_expediente_pkey PRIMARY KEY (involucrado_id, expediente_radicado);


--
-- TOC entry 5053 (class 2606 OID 18076)
-- Name: involucrado_notificacion involucrado_notificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado_notificacion
    ADD CONSTRAINT involucrado_notificacion_pkey PRIMARY KEY (id);


--
-- TOC entry 4989 (class 2606 OID 18078)
-- Name: cesacion ley_1333_2009_etapa_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cesacion
    ADD CONSTRAINT ley_1333_2009_etapa_id_key UNIQUE (etapa_id);


--
-- TOC entry 4991 (class 2606 OID 18080)
-- Name: cesacion ley_1333_2009_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cesacion
    ADD CONSTRAINT ley_1333_2009_pkey PRIMARY KEY (id);


--
-- TOC entry 5061 (class 2606 OID 18082)
-- Name: log_auditoria log_auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_auditoria
    ADD CONSTRAINT log_auditoria_pkey PRIMARY KEY (id);


--
-- TOC entry 5066 (class 2606 OID 18084)
-- Name: medida_preventiva medida_preventiva_etapa_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medida_preventiva
    ADD CONSTRAINT medida_preventiva_etapa_id_key UNIQUE (etapa_id);


--
-- TOC entry 5068 (class 2606 OID 18086)
-- Name: medida_preventiva medida_preventiva_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medida_preventiva
    ADD CONSTRAINT medida_preventiva_pkey PRIMARY KEY (id);


--
-- TOC entry 5070 (class 2606 OID 18088)
-- Name: municipio municipio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT municipio_pkey PRIMARY KEY (id);


--
-- TOC entry 5072 (class 2606 OID 18090)
-- Name: nivel_acto nivel_acto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nivel_acto
    ADD CONSTRAINT nivel_acto_pkey PRIMARY KEY (id);


--
-- TOC entry 5076 (class 2606 OID 18092)
-- Name: notificacion proceso_notificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT proceso_notificacion_pkey PRIMARY KEY (id);


--
-- TOC entry 5078 (class 2606 OID 18094)
-- Name: recurso_afectado recurso_afectado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recurso_afectado
    ADD CONSTRAINT recurso_afectado_pkey PRIMARY KEY (id);


--
-- TOC entry 5080 (class 2606 OID 18096)
-- Name: tipo_cesacion tipo_cesacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_cesacion
    ADD CONSTRAINT tipo_cesacion_pkey PRIMARY KEY (id);


--
-- TOC entry 5090 (class 2606 OID 18098)
-- Name: tipo_sancion tipo_decision_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_sancion
    ADD CONSTRAINT tipo_decision_pkey PRIMARY KEY (id);


--
-- TOC entry 5082 (class 2606 OID 18100)
-- Name: tipo_etapa tipo_etapa_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_etapa
    ADD CONSTRAINT tipo_etapa_nombre_key UNIQUE (nombre);


--
-- TOC entry 5084 (class 2606 OID 18102)
-- Name: tipo_etapa tipo_etapa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_etapa
    ADD CONSTRAINT tipo_etapa_pkey PRIMARY KEY (id);


--
-- TOC entry 5086 (class 2606 OID 18104)
-- Name: tipo_medida tipo_medida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_medida
    ADD CONSTRAINT tipo_medida_pkey PRIMARY KEY (id);


--
-- TOC entry 5088 (class 2606 OID 18106)
-- Name: tipo_notificacion tipo_notificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_notificacion
    ADD CONSTRAINT tipo_notificacion_pkey PRIMARY KEY (id);


--
-- TOC entry 5094 (class 2606 OID 18108)
-- Name: vereda vereda_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vereda
    ADD CONSTRAINT vereda_pkey PRIMARY KEY (id);


--
-- TOC entry 4982 (class 1259 OID 18109)
-- Name: idx_acto_admin_etapa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_acto_admin_etapa ON public.acto_admin USING btree (etapa_id);


--
-- TOC entry 4983 (class 1259 OID 18110)
-- Name: idx_acto_admin_fecha_creacion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_acto_admin_fecha_creacion ON public.acto_admin USING btree (fecha_creacion DESC);


--
-- TOC entry 4984 (class 1259 OID 18111)
-- Name: idx_acto_admin_numerado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_acto_admin_numerado ON public.acto_admin USING btree (numerado);


--
-- TOC entry 4985 (class 1259 OID 18112)
-- Name: idx_acto_admin_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_acto_admin_tipo ON public.acto_admin USING btree (tipo_acto);


--
-- TOC entry 4986 (class 1259 OID 18113)
-- Name: idx_cesacion_etapa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cesacion_etapa ON public.cesacion USING btree (etapa_id);


--
-- TOC entry 4987 (class 1259 OID 18114)
-- Name: idx_cesacion_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cesacion_tipo ON public.cesacion USING btree (tipo_cesacion_id);


--
-- TOC entry 4998 (class 1259 OID 18115)
-- Name: idx_decision_fondo_etapa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_decision_fondo_etapa ON public.decision_fondo USING btree (etapa_id);


--
-- TOC entry 4999 (class 1259 OID 18116)
-- Name: idx_decision_fondo_tipo_sancion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_decision_fondo_tipo_sancion ON public.decision_fondo USING btree (tipo_sancion_id);


--
-- TOC entry 5002 (class 1259 OID 18117)
-- Name: idx_documento_etapa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_documento_etapa ON public.documento USING btree (etapa_id);


--
-- TOC entry 5003 (class 1259 OID 18118)
-- Name: idx_documento_fecha_subida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_documento_fecha_subida ON public.documento USING btree (fecha_subida DESC);


--
-- TOC entry 5004 (class 1259 OID 18119)
-- Name: idx_documento_nombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_documento_nombre ON public.documento USING btree (nombre);


--
-- TOC entry 5009 (class 1259 OID 18120)
-- Name: idx_ejecucion_sancion_cobro; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ejecucion_sancion_cobro ON public.ejecucion_sancion USING btree (cobro_coactivo);


--
-- TOC entry 5010 (class 1259 OID 18121)
-- Name: idx_ejecucion_sancion_etapa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ejecucion_sancion_etapa ON public.ejecucion_sancion USING btree (etapa_id);


--
-- TOC entry 5011 (class 1259 OID 18122)
-- Name: idx_ejecucion_sancion_fecha_auto; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ejecucion_sancion_fecha_auto ON public.ejecucion_sancion USING btree (fecha_auto DESC);


--
-- TOC entry 5014 (class 1259 OID 18123)
-- Name: idx_etapa_expediente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_etapa_expediente ON public.etapa USING btree (expediente_radicado);


--
-- TOC entry 5015 (class 1259 OID 18124)
-- Name: idx_etapa_fecha_inicio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_etapa_fecha_inicio ON public.etapa USING btree (fecha_inicio DESC);


--
-- TOC entry 5016 (class 1259 OID 18125)
-- Name: idx_etapa_radicado_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_etapa_radicado_fecha ON public.etapa USING btree (expediente_radicado, fecha_inicio DESC);


--
-- TOC entry 5017 (class 1259 OID 18126)
-- Name: idx_etapa_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_etapa_tipo ON public.etapa USING btree (tipo_etapa_id);


--
-- TOC entry 5020 (class 1259 OID 18127)
-- Name: idx_expediente_encargado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_encargado ON public.expediente USING btree (encargado_id);


--
-- TOC entry 5021 (class 1259 OID 18128)
-- Name: idx_expediente_encargado_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_encargado_fecha ON public.expediente USING btree (encargado_id, fecha_creacion DESC);


--
-- TOC entry 5022 (class 1259 OID 18129)
-- Name: idx_expediente_fecha_creacion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_fecha_creacion ON public.expediente USING btree (fecha_creacion DESC);


--
-- TOC entry 5023 (class 1259 OID 18130)
-- Name: idx_expediente_nombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_nombre ON public.expediente USING btree (nombre_expediente);


--
-- TOC entry 5024 (class 1259 OID 18131)
-- Name: idx_expediente_radicado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_radicado ON public.expediente USING btree (radicado);


--
-- TOC entry 5028 (class 1259 OID 18132)
-- Name: idx_expediente_recurso_compound; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_recurso_compound ON public.expediente_recurso USING btree (expediente_radicado, recurso_id);


--
-- TOC entry 5029 (class 1259 OID 18133)
-- Name: idx_expediente_recurso_radicado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_recurso_radicado ON public.expediente_recurso USING btree (expediente_radicado);


--
-- TOC entry 5030 (class 1259 OID 18134)
-- Name: idx_expediente_recurso_recurso; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_recurso_recurso ON public.expediente_recurso USING btree (recurso_id);


--
-- TOC entry 5025 (class 1259 OID 18135)
-- Name: idx_expediente_vereda; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_expediente_vereda ON public.expediente USING btree (vereda_id);


--
-- TOC entry 5035 (class 1259 OID 18136)
-- Name: idx_formulacion_cargos_descargos; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_formulacion_cargos_descargos ON public.formulacion_cargos USING btree (descargos);


--
-- TOC entry 5036 (class 1259 OID 18137)
-- Name: idx_formulacion_cargos_etapa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_formulacion_cargos_etapa ON public.formulacion_cargos USING btree (etapa_id);


--
-- TOC entry 5039 (class 1259 OID 18138)
-- Name: idx_involucrado_documento_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_documento_tipo ON public.involucrado USING btree (numero_documento, tipo_documento);


--
-- TOC entry 5043 (class 1259 OID 18139)
-- Name: idx_involucrado_expediente_compound; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_expediente_compound ON public.involucrado_expediente USING btree (expediente_radicado, involucrado_id);


--
-- TOC entry 5044 (class 1259 OID 18140)
-- Name: idx_involucrado_expediente_involucrado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_expediente_involucrado ON public.involucrado_expediente USING btree (involucrado_id);


--
-- TOC entry 5045 (class 1259 OID 18141)
-- Name: idx_involucrado_expediente_radicado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_expediente_radicado ON public.involucrado_expediente USING btree (expediente_radicado);


--
-- TOC entry 5040 (class 1259 OID 18142)
-- Name: idx_involucrado_nombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_nombre ON public.involucrado USING btree (nombre);


--
-- TOC entry 5048 (class 1259 OID 18143)
-- Name: idx_involucrado_notif_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_notif_fecha ON public.involucrado_notificacion USING btree (fecha_notificacion DESC);


--
-- TOC entry 5049 (class 1259 OID 18144)
-- Name: idx_involucrado_notif_involucrado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_notif_involucrado ON public.involucrado_notificacion USING btree (involucrado_id);


--
-- TOC entry 5050 (class 1259 OID 18145)
-- Name: idx_involucrado_notif_notificacion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_notif_notificacion ON public.involucrado_notificacion USING btree (notificacion_id);


--
-- TOC entry 5051 (class 1259 OID 18146)
-- Name: idx_involucrado_notif_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_notif_tipo ON public.involucrado_notificacion USING btree (tipo_notificacion_id);


--
-- TOC entry 5041 (class 1259 OID 18147)
-- Name: idx_involucrado_numero_documento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_numero_documento ON public.involucrado USING btree (numero_documento);


--
-- TOC entry 5042 (class 1259 OID 18148)
-- Name: idx_involucrado_tipo_documento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_involucrado_tipo_documento ON public.involucrado USING btree (tipo_documento);


--
-- TOC entry 5054 (class 1259 OID 18149)
-- Name: idx_log_auditoria_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_log_auditoria_fecha ON public.log_auditoria USING btree (fecha DESC);


--
-- TOC entry 5055 (class 1259 OID 18150)
-- Name: idx_log_auditoria_radicado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_log_auditoria_radicado ON public.log_auditoria USING btree (expediente_radicado);


--
-- TOC entry 5056 (class 1259 OID 18151)
-- Name: idx_log_auditoria_tabla; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_log_auditoria_tabla ON public.log_auditoria USING btree (tabla_afectada);


--
-- TOC entry 5057 (class 1259 OID 18152)
-- Name: idx_log_auditoria_tipo_operacion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_log_auditoria_tipo_operacion ON public.log_auditoria USING btree (tipo_operacion);


--
-- TOC entry 5058 (class 1259 OID 18153)
-- Name: idx_log_auditoria_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_log_auditoria_usuario ON public.log_auditoria USING btree (usuario_id);


--
-- TOC entry 5059 (class 1259 OID 18154)
-- Name: idx_log_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_log_usuario ON public.log_auditoria USING btree (usuario_id);


--
-- TOC entry 5062 (class 1259 OID 18155)
-- Name: idx_medida_preventiva_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_medida_preventiva_estado ON public.medida_preventiva USING btree (estado_medida);


--
-- TOC entry 5063 (class 1259 OID 18156)
-- Name: idx_medida_preventiva_etapa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_medida_preventiva_etapa ON public.medida_preventiva USING btree (etapa_id);


--
-- TOC entry 5064 (class 1259 OID 18157)
-- Name: idx_medida_preventiva_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_medida_preventiva_tipo ON public.medida_preventiva USING btree (tipo_medida_id);


--
-- TOC entry 5073 (class 1259 OID 18158)
-- Name: idx_notificacion_acto_admin; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notificacion_acto_admin ON public.notificacion USING btree (acto_admin_id);


--
-- TOC entry 5074 (class 1259 OID 18159)
-- Name: idx_notificacion_fecha_creacion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notificacion_fecha_creacion ON public.notificacion USING btree (fecha_creacion DESC);


--
-- TOC entry 5091 (class 1259 OID 18160)
-- Name: idx_vereda_municipio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vereda_municipio ON public.vereda USING btree (municipio_id);


--
-- TOC entry 5092 (class 1259 OID 18161)
-- Name: idx_vereda_nombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vereda_nombre ON public.vereda USING btree (nombre);


--
-- TOC entry 5095 (class 2606 OID 18162)
-- Name: acto_admin acto_admin_id_etapa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.acto_admin
    ADD CONSTRAINT acto_admin_id_etapa_fkey FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);


--
-- TOC entry 5098 (class 2606 OID 18167)
-- Name: comunicacion comunicacion_acto_admin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comunicacion
    ADD CONSTRAINT comunicacion_acto_admin_id_fkey FOREIGN KEY (acto_admin_id) REFERENCES public.acto_admin(id);


--
-- TOC entry 5099 (class 2606 OID 18172)
-- Name: decision_fondo decision_fondo_etapa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.decision_fondo
    ADD CONSTRAINT decision_fondo_etapa_id_fkey FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);


--
-- TOC entry 5100 (class 2606 OID 18177)
-- Name: decision_fondo decision_fondo_id_tipo_sancion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.decision_fondo
    ADD CONSTRAINT decision_fondo_id_tipo_sancion_fkey FOREIGN KEY (tipo_sancion_id) REFERENCES public.tipo_sancion(id);


--
-- TOC entry 5101 (class 2606 OID 18182)
-- Name: documento documento_id_etapa__fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documento
    ADD CONSTRAINT documento_id_etapa__fkey FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);


--
-- TOC entry 5102 (class 2606 OID 18187)
-- Name: ejecucion_sancion ejecucion_sancion_etapa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejecucion_sancion
    ADD CONSTRAINT ejecucion_sancion_etapa_id_fkey FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);


--
-- TOC entry 5103 (class 2606 OID 18192)
-- Name: etapa etapa_expediente_radicado_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etapa
    ADD CONSTRAINT etapa_expediente_radicado_fkey FOREIGN KEY (expediente_radicado) REFERENCES public.expediente(radicado) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 5104 (class 2606 OID 18197)
-- Name: etapa etapa_tipo_etapa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etapa
    ADD CONSTRAINT etapa_tipo_etapa_id_fkey FOREIGN KEY (tipo_etapa_id) REFERENCES public.tipo_etapa(id);


--
-- TOC entry 5106 (class 2606 OID 18202)
-- Name: expediente_recurso expediente_recurso_expediente_radicado_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expediente_recurso
    ADD CONSTRAINT expediente_recurso_expediente_radicado_fkey FOREIGN KEY (expediente_radicado) REFERENCES public.expediente(radicado) ON DELETE CASCADE;


--
-- TOC entry 5105 (class 2606 OID 18207)
-- Name: expediente expediente_vereda_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expediente
    ADD CONSTRAINT expediente_vereda_id_fkey FOREIGN KEY (vereda_id) REFERENCES public.vereda(id);


--
-- TOC entry 5107 (class 2606 OID 18212)
-- Name: expediente_recurso fk_exp_radicado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expediente_recurso
    ADD CONSTRAINT fk_exp_radicado FOREIGN KEY (expediente_radicado) REFERENCES public.expediente(radicado) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 5112 (class 2606 OID 18217)
-- Name: involucrado_notificacion fk_notificaciopn_tipo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado_notificacion
    ADD CONSTRAINT fk_notificaciopn_tipo FOREIGN KEY (tipo_notificacion_id) REFERENCES public.tipo_notificacion(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 5108 (class 2606 OID 18222)
-- Name: expediente_recurso fk_recurso; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expediente_recurso
    ADD CONSTRAINT fk_recurso FOREIGN KEY (recurso_id) REFERENCES public.recurso_afectado(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 5096 (class 2606 OID 18227)
-- Name: cesacion fk_tipo_cesacion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cesacion
    ADD CONSTRAINT fk_tipo_cesacion FOREIGN KEY (tipo_cesacion_id) REFERENCES public.tipo_cesacion(id);


--
-- TOC entry 5109 (class 2606 OID 18232)
-- Name: formulacion_cargos formulacion_cargos_etapa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formulacion_cargos
    ADD CONSTRAINT formulacion_cargos_etapa_id_fkey FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);


--
-- TOC entry 5110 (class 2606 OID 18237)
-- Name: involucrado_expediente involucrado_expediente_expediente_radicado_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado_expediente
    ADD CONSTRAINT involucrado_expediente_expediente_radicado_fkey FOREIGN KEY (expediente_radicado) REFERENCES public.expediente(radicado) ON UPDATE CASCADE;


--
-- TOC entry 5111 (class 2606 OID 18242)
-- Name: involucrado_expediente involucrado_expediente_involucrado_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado_expediente
    ADD CONSTRAINT involucrado_expediente_involucrado_id_fkey FOREIGN KEY (involucrado_id) REFERENCES public.involucrado(id) ON DELETE CASCADE;


--
-- TOC entry 5113 (class 2606 OID 18247)
-- Name: involucrado_notificacion involucrado_notificacion_involucrado_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado_notificacion
    ADD CONSTRAINT involucrado_notificacion_involucrado_id_fkey FOREIGN KEY (involucrado_id) REFERENCES public.involucrado(id);


--
-- TOC entry 5114 (class 2606 OID 18252)
-- Name: involucrado_notificacion involucrado_notificacion_notificacion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.involucrado_notificacion
    ADD CONSTRAINT involucrado_notificacion_notificacion_id_fkey FOREIGN KEY (notificacion_id) REFERENCES public.notificacion(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 5097 (class 2606 OID 18257)
-- Name: cesacion ley_1333_2009_etapa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cesacion
    ADD CONSTRAINT ley_1333_2009_etapa_id_fkey FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);


--
-- TOC entry 5115 (class 2606 OID 18262)
-- Name: log_auditoria log_auditoria_expediente_radicado_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_auditoria
    ADD CONSTRAINT log_auditoria_expediente_radicado_fkey FOREIGN KEY (expediente_radicado) REFERENCES public.expediente(radicado) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 5116 (class 2606 OID 18267)
-- Name: medida_preventiva medida_preventiva_etapa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medida_preventiva
    ADD CONSTRAINT medida_preventiva_etapa_id_fkey FOREIGN KEY (etapa_id) REFERENCES public.etapa(id);


--
-- TOC entry 5117 (class 2606 OID 18272)
-- Name: medida_preventiva medida_preventiva_id_tipo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medida_preventiva
    ADD CONSTRAINT medida_preventiva_id_tipo_fkey FOREIGN KEY (tipo_medida_id) REFERENCES public.tipo_medida(id);


--
-- TOC entry 5118 (class 2606 OID 18277)
-- Name: notificacion notificacion_acto_admin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_acto_admin_id_fkey FOREIGN KEY (acto_admin_id) REFERENCES public.acto_admin(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 5119 (class 2606 OID 18282)
-- Name: vereda vereda_municipio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vereda
    ADD CONSTRAINT vereda_municipio_id_fkey FOREIGN KEY (municipio_id) REFERENCES public.municipio(id);


--
-- TOC entry - Tabla file_hash para deduplicación de archivos
-- Name: file_hash; Type: TABLE; Schema: public; Owner: postgres
--

-- Migración: Crear tabla file_hash para deduplicación de archivos
-- Fecha: 2026-02-12
-- Descripción: Esta tabla almacena hashes SHA256 de archivos para evitar duplicados en MinIO

-- Crear tabla file_hash
CREATE TABLE IF NOT EXISTS public.file_hash (
    id SERIAL PRIMARY KEY,
    file_hash VARCHAR(64) NOT NULL UNIQUE,  -- Hash SHA256 (64 caracteres hexadecimales)
    file_url TEXT NOT NULL,                 -- URL del archivo en MinIO (bucket/path)
    original_filename VARCHAR(255),         -- Nombre original del primer archivo con este hash
    content_type VARCHAR(100),              -- MIME type del archivo (application/pdf, image/jpeg, etc.)
    file_size INTEGER,                      -- Tamaño del archivo en bytes
    reference_count INTEGER DEFAULT 1,      -- Contador de referencias (cuántas veces se usa)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_referenced_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE public.file_hash OWNER TO postgres;

-- Crear índice único para búsquedas rápidas por hash
CREATE UNIQUE INDEX IF NOT EXISTS ix_file_hash_unique ON public.file_hash(file_hash);

-- Crear índice para búsquedas de archivos huérfanos (sin referencias)
CREATE INDEX IF NOT EXISTS ix_file_hash_ref_count ON public.file_hash(reference_count);

-- Crear índice para búsquedas por fecha de creación
CREATE INDEX IF NOT EXISTS ix_file_hash_created ON public.file_hash(created_at);

-- Comentarios para documentación
COMMENT ON TABLE public.file_hash IS 'Tabla de deduplicación de archivos. Almacena hashes SHA256 para evitar duplicados en MinIO';
COMMENT ON COLUMN public.file_hash.file_hash IS 'Hash SHA256 del contenido del archivo (64 caracteres hexadecimales)';
COMMENT ON COLUMN public.file_hash.file_url IS 'URL del archivo en MinIO en formato bucket/path';
COMMENT ON COLUMN public.file_hash.reference_count IS 'Número de veces que este archivo está siendo referenciado. 0 = archivo huérfano que puede ser eliminado';
COMMENT ON COLUMN public.file_hash.last_referenced_at IS 'Última vez que se creó o reutilizó una referencia a este archivo';

-- Función para actualizar last_referenced_at y reference_count cuando se reutiliza un archivo
CREATE OR REPLACE FUNCTION update_file_hash_reference()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_referenced_at = CURRENT_TIMESTAMP;
    NEW.reference_count = COALESCE(NEW.reference_count, 0) + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Permisos
GRANT SELECT, INSERT, UPDATE ON public.file_hash TO PUBLIC;
GRANT USAGE ON SEQUENCE public.file_hash_id_seq TO PUBLIC;


-- Completed on 2026-02-10 09:11:16

--
-- PostgreSQL database dump complete
--

\unrestrict jio4YxXmYb9ms2oNv8DBUnE0PpTHIllOOsNcW3EJ39BSjWHqqGGjrXB2IfCIZtn

