CREATE TABLE "expediente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "radicado" varchar(15) UNIQUE,
  "fecha_radicado" date,
  "vereda_id" integer,
  "requiere_medida_preventiva" boolean,
  "presunto_infractor_id" bigint,
  "fecha_creacion" timestamptz NOT NULL,
  "abogado_responsable_id" integer,
  "predio" varchar(100),
  "descripcion" varchar(300),
  "causa_id" integer
);

CREATE TABLE "quejoso" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150),
  "telefono" varchar(10),
  "correo" varchar(100)
);

CREATE TABLE "quejoso_expediente" (
  "quejoso_id" integer,
  "expediente_id" integer
);

CREATE TABLE "recurso_afectado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(15)
);

CREATE TABLE "recurso_expediente" (
  "expediente_id" integer,
  "recurso_id" integer
);

CREATE TABLE "vereda" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30),
  "id_municipio" integer
);

CREATE TABLE "municipio" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30)
);

CREATE TABLE "causa" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(20)
);

CREATE TABLE "radicado_asociado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "radicado" varchar(15) UNIQUE,
  "expediente_id" integer
);

CREATE TABLE "etapa_respuesta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "expediente_id" integer,
  "radicado" varchar(15) UNIQUE,
  "fecha_radicado" date,
  "documento_radicado_id" integer,
  "medida_preventiva" boolean
);

CREATE TABLE "informe_tecnico" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "expediente_id" integer,
  "profesional_asignado" integer,
  "fecha_programacion_visita" date,
  "fecha_recibido_informe" date,
  "fecha_entrega_informe" date,
  "documento_informe_id" integer,
  "tipo_informe" varchar(20)
);

CREATE TABLE "etapa_concepto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "expediente_id" integer,
  "fecha_auto_indagacion" date,
  "termino" integer,
  "fecha_termino_calculada" date,
  "acto_administrativo_id" integer,
  "fecha_creacion" timestamptz NOT NULL
);

CREATE TABLE "acto_administrativo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numerado" integer,
  "fecha_numerado" date,
  "fecha_asigncion_juridica" date,
  "documento_acto_administrativo_id" integer,
  "fecha_creacion" timestamptz NOT NULL
);

CREATE TABLE "notificacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_creacion" date,
  "acto_administrativo_id" integer,
  "numerado" integer,
  "fecha_numerado" date,
  "fecha_envio_citacion" date,
  "fecha_constancia_citacion" date,
  "documento_citacion_id" integer,
  "notificacion_exitosa" boolean,
  "fecha_notificacion" timestamptz NOT NULL,
  "tipo_notificacion_id" integer,
  "documento_notificacion_id" integer
);

CREATE TABLE "tipo_notificacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(15)
);

ALTER TABLE "expediente" ADD CONSTRAINT "vereda_expediente" FOREIGN KEY ("vereda_id") REFERENCES "vereda" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vereda" ADD CONSTRAINT "municipio_vereda" FOREIGN KEY ("id_municipio") REFERENCES "municipio" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "quejoso_expediente" ADD CONSTRAINT "quejoso_expediente" FOREIGN KEY ("quejoso_id") REFERENCES "quejoso" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "quejoso_expediente" ADD CONSTRAINT "expediente_quejoso" FOREIGN KEY ("expediente_id") REFERENCES "expediente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recurso_expediente" ADD CONSTRAINT "recurso_expediente" FOREIGN KEY ("recurso_id") REFERENCES "recurso_afectado" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recurso_expediente" ADD CONSTRAINT "expediente_recurso" FOREIGN KEY ("expediente_id") REFERENCES "expediente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "causa" ADD CONSTRAINT "expediente_causa" FOREIGN KEY ("id") REFERENCES "expediente" ("causa_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "radicado_asociado" ADD CONSTRAINT "expediente_asociados" FOREIGN KEY ("expediente_id") REFERENCES "expediente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "etapa_respuesta" ADD CONSTRAINT "expediente_respuesta" FOREIGN KEY ("expediente_id") REFERENCES "expediente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "informe_tecnico" ADD CONSTRAINT "expediente_visita" FOREIGN KEY ("expediente_id") REFERENCES "expediente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expediente" ADD CONSTRAINT "expediente_concepto" FOREIGN KEY ("id") REFERENCES "etapa_concepto" ("expediente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "acto_administrativo" ADD CONSTRAINT "concepto_acto" FOREIGN KEY ("id") REFERENCES "etapa_concepto" ("acto_administrativo_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacion" ADD CONSTRAINT "acto_notificacion" FOREIGN KEY ("acto_administrativo_id") REFERENCES "acto_administrativo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tipo_notificacion" ADD CONSTRAINT "notificacin_tipo" FOREIGN KEY ("id") REFERENCES "notificacion" ("tipo_notificacion_id") DEFERRABLE INITIALLY IMMEDIATE;
